### ISSUE TITLE
Find the uuid in LG webos tv is not correct,it is just the app name,not the device uuid.

### ISSUE THREAD

**Issue by kingctan** [mautilus/sdk#10]
Find the uuid in LG webos tv is not correct,it is just the app name,not the device uuid.
How to get the device id on LG webos tv ? should be unique.
Thanks.

**Comment by stenlik** [comment]
LG webOS devices do not have unfortunately fixed UUID available. You have to generate it and save to the cookies of your application + handle the cookies expiration.

**Comment by stenlik** [comment]
Hi,

Did the answer help you? If yes please close the issue.

Thanks
Mautilus SmartTV SDK Team

**Comment by kingctan** [comment]
OK,thanks.
