### ISSUE TITLE
Installation of the development application on LG TV 60LA860V

### ISSUE THREAD

**Issue by stenlik** [mautilus/sdk#11]
_Received via email_
Hello dears
Can you help me.
I'm a web developer and now I'm working on app for LG smart TV. I need to test my app on real TV. My TV model is 60LA860V. When I want to connect USB or HDMI, there need to login. I can't find developer mode in this model. Please help me. How can I login on TV?
thanks in advacne

**Comment by stenlik** [comment]
Hello,

The 60LA860V is a standard LG NetCast TV model. There is not any developer mode. You have to sign-in as as a normal user, copy application on USB in the defined structure and consequently you can start the application from the USB. It is quite straightforward.

Kind Regards,
Petr Mazanec

**Comment by vnaira** [comment]
Where I have to sign in? In TV? I didn't find in this model someplace to login.?

**Comment by streitdaniel** [comment]
Hi vnaira,
In the My apps is the icon Sign In on the top of the screen (it is on the right by Search icon), there you can Sing In or Sign Up.

Best Regards
Daniel Streit

**Comment by stenlik** [comment]
Hi,

Did the answer help you? If yes please close the issue.

Thanks
Mautilus SmartTV SDK Team
