### ISSUE TITLE
package generation for tizen and webos platforms

### ISSUE THREAD

**Issue by Rkdroid** [mautilus/sdk#13]
Hi,
in the given demo examples, the package generation done through gruntfile for tizen doesn't result in the expected .wgt file where as by default in the demos package folder you have the tizen zip file on extraction of which where we have the .wgt file, if we generate grunt build for the tizen platform. the package is no different from the legacy orsay platform? are we missing something here?

the grunt file doesn't have the webOS build generation can you please help on that too.

Thanks

**Comment by streitdaniel** [comment]
Hi Rkdroidm

That is because both platforms needed their own IDE installed, must be build in SDK (Tizen) or exe files from their SDK is needed (webOS).

**Comment by Rkdroid** [comment]
Hi Daniel,
Thanks for the info, can you please provide your point on developing the smart tv application on angularJS platform, specific to using it for the user interface part. with the approach you have currently it will be little difficult to achieve the separations of concerns as there is a lot of html sitting in JS code.

Thanks

**Comment by streitdaniel** [comment]
Hi Rkdroid,
So, we doesn't use angularJS, but you can use some of templates frameworks.

**Comment by Rkdroid** [comment]
yeah, i have tried with handlebars it works okay, but do you see any drawbacks of developing the app on Angular JS framework, example:  might be resource heavy which in turn can lead to lag in UI navigation especially with grids.
do you see this as a problem or should be fine going head with angularJS for development?

**Comment by streitdaniel** [comment]
Be aware, most of old televisions have not good performance. This also applies for example to css and javascript animations.

**Comment by stenlik** [comment]
Hi Rkdroid,

Did the answer help you? If yes please close the issue.

Thanks
Mautilus SmartTV SDK Team

**Comment by Rkdroid** [comment]
Thanks Daniel, it was helpful.
