### ISSUE TITLE
Problem on Samsung Orsay

### ISSUE THREAD

**Issue by jorgitoml** [mautilus/sdk#16]
I've developed an app for Samsung Orsay platform.
The app works fine in the Orsay emulator, but when I install it on a real device the TV crashes and reboots.
Have you noticed this anytime? Any clue?
Thanks!

**Comment by SoCoxx** [comment]
How did you installed your application? Via widgetlist.xml over webserver, or via USB?

**Comment by jorgitoml** [comment]
Via widgetlist.xml over webserver.

**Comment by stenlik** [comment]
I see there two options: 

1) Either you send us the application package and we try to debug it and find the issue. In such a case send us please also your Orsay TV model you are using for testing.

2) Alternative way is commenting out the code you call during your application startup, ensuring the application starts and using the bisection method start uncommenting the code until you find the line that causes the problem.

**Comment by jorgitoml** [comment]
*TV:
-Model: UE32F4500
-Firm: T-MST12DEUC-2115.1

And here is the package:
http://we.tl/VPlktvLHc7

Tx!

**Comment by stenlik** [comment]
Thanks a lot! We will check it.

**Comment by SoCoxx** [comment]
We've tested it on the UE32F5300 (most closest model to your) and it is working http://s15.postimg.org/traym4ojv/IMG_20160315_071743.jpg

**Comment by jorgitoml** [comment]
Did you installed the app via widgetlist.xml?
Your device is using the same firmware as mine?

**Comment by jorgitoml** [comment]
I've detected the problem...it's a resolution problem.
My tv does not accept 1920x1080.
Is there any way to detect the device resolution?
Regards.

**Comment by SoCoxx** [comment]
My advise is using:
Use Alpha Blending? = Yes
Screen Resolution = 1280x720
in widget.info

To detect the resolution, use screen.width and screen.height in javascript.

**Comment by jorgitoml** [comment]
OK, thaks.

**Comment by SoCoxx** [comment]
And one more tip - you don't need to watch the focus. Anytime you use Focus.to($jQueryElement) on element that has class "focusable", it adds "focus" class automatically. And also removes the "focus" class from previously focused element. Then just make CSS selector like #someId > div.focusable {} ; #someId > div.focusable.focus {border 2px solid red};

**Comment by stenlik** [comment]
I suggest using 1280x720px – it is universally supported by all 2012+ TVs (not only Samsung).

**Comment by jorgitoml** [comment]
Perfect, tx!
