### ISSUE TITLE
delete scene in history

### ISSUE THREAD

**Issue by kingctan** [mautilus/sdk#19]
A scenarios like:

open login scene  ------>  input username,password, then login  ------>auto goto logined scene.
Then click the back button, the scene will go back to login scene.

How to fix this, if i need delete the login scene in history?
Thanks.

**Comment by alfredo86** [comment]
Hi,

thanks for your answer.

I think you currently use something like this. right?
    Router.go("login"); // router goes to the login scene

If you do not want to add some scene to history you should something like this:
    Router.go(false, "login"); // flag false (must be set as first parameter) force to no adding login scene to the scene history.

I hope that it is useful for you :-)

**Comment by mautilus** [comment]
Exactly as alfredo86 answered. Router.go() has 2 "overloads":
- go to the scene and push it to history, so you can return back via Router.goBack()

`Router.go("login");`
- go to the scene but DO NOT push it into history

`Router.go(false,"login");`

**Comment by kingctan** [comment]
OK
Thank you @alfredo86 @mautilus
