### ISSUE TITLE
Player.fullscreen() & Mouse

### ISSUE THREAD

**Issue by jorgitoml** [mautilus/sdk#21]
Hi,
I have a scene with a player in full-screen mode and several focusable elements in front of it.
If the player is in window mode, I can focus these elements, but when the player is in full-screen mode, the mouse focus events are lost.
Can you tell me what I'm doing wrong?
Best regards.

**Comment by mautilus** [comment]
Probably only low z-index of these elements.
It is good to have one player-sized div overlaying the player. It can capture all mouse/pointer clicks that will show snippet with Player controls (stop/ff/rew/...) and progress bar.

**Comment by jorgitoml** [comment]
I already tried incrementing the z-index without success.
I'll try using an snippet.
Thx!
