### ISSUE TITLE
app.notification be added to secene's history

### ISSUE THREAD

**Issue by kingctan** [mautilus/sdk#23]
I invoked App.notification() function in one scene, after msg hide,I click back button on remote control. Then the msg show again.
Please check it, maybe it's a bug.
Thanks.

**Comment by SoCoxx** [comment]
Where did you invoked `App.notification()`? When you are going back, `activate()` and `render()` are called again

**Comment by kingctan** [comment]
in the play scene,when open play scene with no url, then error info notified, after msg hidden, press the back button, the msg panel show again.

**Comment by SoCoxx** [comment]
send the application example please, so I can check it
