### ISSUE TITLE
Player.reset() issue.

### ISSUE THREAD

**Issue by jorgitoml** [mautilus/sdk#26]
In the new release, you changed thie Player.reset() method from:
`function() {
this.url = null;
this.duration = 0;
this.currentTime = 0;
this.currentState = this.STATE_IDLE;
this.speed = 1;
this.width = this.config.width;
this.height = this.config.height;
this.trigger('reset');
},`
To:
`function() {
this.url = null;
this.duration = 0;
this.currentTime = 0;
this.currentState = this.STATE_IDLE;
this.speed = 1;
this.width = this.config.width;
this.height = this.config.height;
this.drmType = '';
this.customData = null;
this.trigger('reset');
},`

The Player.reset() method is always called before play an URL (see Player.setUrl() method), so if the stream is DRMed the customData will be always NULL and no information will be sent to the DRM server...and the stream will not play.

Please, delete this lines in the method:
`this.drmType = '';
this.customData = null;`

Also I've modified the core to allow set a custom DRM server url...I can share it with you if you want.

Regards.

**Comment by jorgitoml** [comment]
I've also noticed that on Samsung Orsay devices, when you try to play a DRMed stream for the very first time (the TV doesn't have the DRM license stored), the stream doesn't play but the player asks for the licence and stores it. The following times, the player doesn't ask for the license but the stream plays without problem until the stored licence expires.

Any clue to solve this?

**Comment by jorgitoml** [comment]
One more thing.
In LG Netcast devices
this.DRMAGENT = document.getElementById("drmAgent");
Is allways null...so I can't play playready DRM contents.
Can you tell me how to fix it?
Regards.

EDIT
Solved changing:
`this.DRMAGENT = document.getElementById("drmAgent");`
with:
`this.$el = $('<object type="application/oipfDrmAgent" id="drmAgent" width="0" height="0"></object>').appendTo('body');
this.DRMAGENT = this.$el[0];`

**Comment by radimbuchtela** [comment]
jorgitoml - Many thanks for your useful feedbacks. It will be included in next release version where interface for DRM video playing is slightly reworked.

Regards,
Radim

**Comment by jorgitoml** [comment]
You are welcome.
