### ISSUE TITLE
LG webos TV remote control not work with page up and page down button.

### ISSUE THREAD

**Issue by kingctan** [mautilus/sdk#27]
LG webos TV remote control not work with page up and page down button. please check it. Thanks.

**Comment by radimbuchtela** [comment]
Hi kingctan,
it should work fine. I tested it on LG webOS 1.0 and LG webOS 2.0.

``` javascript
Control.on('key', function(keycode) {
  if(keycode == Control.key.PUP) {  // keycode 33
    console.log('pressed key PUP');
  }
  if(keycode == Control.key.PDOWN) {  // keycode 34
    console.log('pressed key PDOWN');
  }
});
```

Only note: You should have a closed Debug console for proper propagation of PUP and PDOWN keyDown event. If Debug console has a open window, then PUP and PDOWN keydown event is internally used for scrolling of text inside this debug console window.

Radim

**Comment by kingctan** [comment]
OK thanks.
