### ISSUE TITLE
Any chance to include support for Samsung SmartTV 2011?

### ISSUE THREAD

**Issue by msfilho** [mautilus/sdk#3]
Any chance to include support for Samsung SmartTV 2011?

**Comment by stenlik** [comment]
Samsung SmartTV 2011 TV platform has many technical and performance limitations, limited support for streaming protocols, bugs in firmware, which will never be fixed, etc. Its generic support in SDK will impose unwanted limitations to applications for other platforms. We do not plan to support those old models. However in the past for specific projects we were adapting SDK and applications to 2011 models, so it is possible. You can adopt it on your own.

**Comment by stenlik** [comment]
Is there anything else we could help? If not please close the issue.

**Comment by msfilho** [comment]
No, thank you for answer...
