### ISSUE TITLE
Problem with  Playing MPEG-DASH (Samsung Orsay 2012)

### ISSUE THREAD

**Issue by nikitalaletin** [mautilus/sdk#30]
Hello!
I've used your example "PlayerKeyboardInfo" for playing different types of streams. Playready and Widevine steams work correctly without any problems) But, when i try to play .mpd file, there is an error in the player console "3, render"(OnRenderError function in player.js). 

Info:
Device: Samsung TV 2012;
Firmware: T-INFOLINK2012-1026;
SDK Version: 2.0.220 (02.12.2015);

I run my app on TV using widgetlist.xml

Here is .mpd - test links i've tested(without 4K) from http://dashif.org/reference/players/javascript/nightly/dash.js/samples/dash-if-reference-player/index.html
(but no one with correct result):

1) http://media.axprod.net/TestVectors/v6-Clear/Manifest_1080p.mpd
2)http://wowzaec2demo.streamlock.net/vod/_definst_/ElephantsDream/smil:ElephantsDream.smil/manifest_mvtime.mpd

Could you tell me how to fix this problem(or provide correct MPEG-DASH link)?
Thank you in advance)

Link for my project , insert stream link to CONFIG.video in config.js
https://github.com/nikitalaletin/Orsay-Playready-Player

**Comment by stenlik** [comment]
MPEG-DASH is not supported on 2012 devices.
