### ISSUE TITLE
Are you going to support Samsung D serie devices?

### ISSUE THREAD

**Issue by catbaxter** [mautilus/sdk#31]
Got the following exception on emulator:

[JAVASCRIPT ERROR]
  File         : file://localhost/D:\programme\Samsung%20TV%20SDK(2.5.1)\Emulator\Emulator2011_v2.5\commonlib//Common/API/Plugin.js
  Line No      : 199
  Error Detail : TypeError: Plugin.NNAVI.Object.GetPluginInfo is not a function

**Comment by stenlik** [comment]
Hello, 'D' series are 2011 devices right? Those we are not supporting.

**Comment by catbaxter** [comment]
Jep, they are 2011 devices. Pity.

**Comment by stenlik** [comment]
Those devices bring more troubles (low performance, low resolution, issues in FW, which will not be fixed, own internal web core, limited support of DOM/JS/CSS) and maintenance costs then real benefits. The user base is not big and it is getting smaller every day.

But it is still better then 'C' serie :)

**Comment by catbaxter** [comment]
I see, agree the hardware and software of the D serie are awful.
