### ISSUE TITLE
General question on SDK and packaging

### ISSUE THREAD

**Issue by jayjayzheng** [mautilus/sdk#32]
Not sure if this is the right place to post the questions but couldn't find anywhere else. If the questions below are not appropriate, please let me know where should be a more suitable place.

My questions are - 
1. what are the recommended IDE that Mautilus team would use for the SDK development?
2. how does Mautilus team package the apps into different TV platforms?

Thanks.

**Comment by radimbuchtela** [comment]
Hi jayjayheng,
1) Most of the team use Eclipse IDE (main reason for this choise is Samsung, Tizen and LG webOS IDE is based on Eclipse IDE too). But of course it is not a requirement for using Mautilus SDK.
2) We use Grunt.js to make packages for each platform. Our Grunt.js script generally runs in these steps:
- select only JS drivers for selected TV platform
- select only assets (app icons, config files) specified for selected TV platform
- make minimalization of JS, CSS, HTML sources
- output is package.zip for selected TV platform

Regards,
Radim

**Comment by jayjayzheng** [comment]
Hi Radim,

Thanks a lot for your quick response. Your SDK is awesome and I'd like to explore more into it. But the online resource seems to be limited other than your SDK API doc. Could you please share any other valuable sites/resources/docs that would help starters to get up to speed to use your SDK for development?

Also, I have a specific question - is there a way that through the SDK, we can programmatically change the input source of the TV? For example, a person is watching TV programs via cable connection, a TV app is running in background and once the timing is up, it fires a event to change the input source of the TV to broadcast some custom content, and then switch it back after some time. Is it even possible?

again, thanks very much for your insights.

**Comment by SoCoxx** [comment]
Hello.

There are examples you can look at, and source code (js/core/module/*). SDK is very easy to understand :)

I'm afraid, there is no way on any platform, that you can change input source of TV from running application. If it is, it will be platform specific and done using proprietary objects.

Feel free to ask any questions related to Mautilus Smart TV SDK

**Comment by jayjayzheng** [comment]
Thank you!
