### ISSUE TITLE
How to handle multitasking?

### ISSUE THREAD

**Issue by jorgitoml** [mautilus/sdk#33]
Do you have any multitasking sample for tizen&webos devices? 

My app has a "login" scene and a "player" scene.
If the user is in "player" scene and hides the app, when returning, the "login" scene is shown instead of "player" scene. 

Can you tell me how to return directly to the "player" scene to continue playing?

Best regards.

**Comment by jorgitoml** [comment]
Nobody?

**Comment by SoCoxx** [comment]
Which platform are you interested in? Tizen or WebOS?

**Comment by jorgitoml** [comment]
Tizen.
Thanks for your reply.

**Comment by SoCoxx** [comment]
Does it work on other applications on your device?

And one more question: When testing, does application reset only 1st time and after this it holds the state?

**Comment by jorgitoml** [comment]
Ooops, It doesn't work on my Tizen device (I've tested with Youtube app)...but Samsung testers noticed this problem when I tried to register my app.

**Comment by SoCoxx** [comment]
As i know, not all Tizen devices support multitasking. I will try to get some more info about this.

What is your model (i.e. UE43KU6072) ?

**Comment by jorgitoml** [comment]
OK, but my app was rejected on tizen devices due the multitasking issue.
My model is: UE32J5570

**Comment by SoCoxx** [comment]
Hi,

the most closest model to yours that we have is UE32J5600 and this mode doesn't support multitasking.

Could you please send me the complain from samsung seller about missing multitasking? It might be something else

**Comment by jorgitoml** [comment]
Take a look:
http://puu.sh/riTY3/ca033f4f7d.png
http://puu.sh/riU4f/d4eceda63a.png
http://puu.sh/riUfM/9635b24381.png
http://puu.sh/riUnA/8fdbf51e0f.png

**Comment by SoCoxx** [comment]
Hi,

most of problems are instant on - when pressing power off button (for less than few seconds) while application is playing video and then powering it back. This should be handled in SDK (please check if you have latest version)
1. instant on problem. 
2. same problem - instant on
3. they have added this feature just now - this should solve problem https://www.samsungdforum.com/TizenGuide/tizen4091/index.html
4. same problem - instant on

About multitasking/instant on:

in both cases (powering off tv / switching application), event 'visibilitychange' is emitted. This is also when switching back to application and powering TV again. SDK's Device_Tizen is translating them as 
Device.trigger('hideApp') and Device.trigger('resumeApp'). These events are watched by SDK's Player_Tizen that is handling all logic behind with suspending player with webapis.avplay.suspend() and restarting stream and setting position webapis.avplay.restore().

**Comment by jorgitoml** [comment]
Yes, I'm using the latest version. 
versionSDK: '2.0.230 [02.05.2016]',

**Comment by SoCoxx** [comment]
I will try to make a demo application for this purpose today, test it and then share it

**Comment by jorgitoml** [comment]
OK
Thanks a lot SoCoxx.

**Comment by SoCoxx** [comment]
Hello,

I will need some more time, as it seems that Samsung changed instant on in their latest firmware and it is not working anymore on Tizen 2015 models. This might be a platform bug, but we need to make some research about it.

Thanks

**Comment by jorgitoml** [comment]
OK, no problem.
Best regards.

**Comment by jorgitoml** [comment]
Hi SoCoxx,
any news?
Best regards.

**Comment by SoCoxx** [comment]
Nope, we are still communicating with Samsung QA. We are trying to explain them, that the bug is on their side

**Comment by jorgitoml** [comment]
Sorry for harping on about it, but...any changes?

**Comment by jorgitoml** [comment]
Bump
