### ISSUE TITLE
Wrong video scale on Tizen 16TV_STANDARD2 devices

### ISSUE THREAD

**Issue by jorgitoml** [mautilus/sdk#35]
![wrong scale](https://cloud.githubusercontent.com/assets/1795137/19161788/839803f4-8bf5-11e6-872b-34d299c2f8a1.jpg)

Video scale is wrong on Samsung Tizen 16TV_STANDARD2 devices...in the rest of Samsung devices the video is displayed fine.
Could you check this?
Best regards.

**Comment by SoCoxx** [comment]
Hi, what type of stream is it? HLS/MP4/... ? When do you use other stream like big buck bunny (http://camendesign.com/code/video_for_everybody/test.html), problem still persists?

**Comment by jorgitoml** [comment]
Player Specification:
Video Codec - H.264
Audio Codec - AAC
Container Codec - MP4
DRM Codec - Playready
Protocol Codec - HTTP

Sorry, I can't test with this stream on a 2016 device...my Tizen device is from 2015.
The bug was reported by Samsung Sellers Office.

**Comment by jorgitoml** [comment]
May be "webapis.productinfo.isUdPanelSupported()" is not working fine in some 2016 devices?

https://www.samsungdforum.com/SamsungDForum/ForumView/9d322f0f492a38d7?forumID=13ddc14a497e5e64

"So you should not use isUdPanelSupported method to check app resolution. It'll make error on 16year's TV
Please use Tizen SystemInfo API to check resolution."

**Comment by jorgitoml** [comment]
Samsung's answer:
![ss 2016-10-13 at 04 12 25](https://cloud.githubusercontent.com/assets/1795137/19352403/ff9a61c6-915f-11e6-9267-271f2eab4254.png)

**Comment by radimbuchtela** [comment]
Hi jorgitoml,
thanks for your information. Fix will be included in next release.

Solution with  "webapis.productinfo.isUdPanelSupported()" was working fine on all Tizen TV 2015, but as you noted it falls on 16TV_STANDARD2 models.

I attached .zip how it can be quick fixed.
[tizen_player.zip](https://github.com/mautilus/sdk/files/527666/tizen_player.zip)

Regards,
Radim
