### ISSUE TITLE
Samsung Player does not play content

### ISSUE THREAD

**Issue by bakikocak** [mautilus/sdk#36]
I am trying to play a sample content on Samsung Smart TV (2014, Orsay) using Mautilus. But it does not play nor throws an error. Is there anyone who faced any problem or knows that we need to do any changes on Mautilus to be able to play a content. Here is the link for the sample content.

http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8

Thanks.

**Comment by radimbuchtela** [comment]
Hi,
you are right. The error is occured during playing this stream on Samsung 2014 (This error is thrown at 10 seconds of video in our case). TV reports some error regarding to rendering. On Samsung 2012, 2013 this stream works ok.

I recomend to test some other HLS or .mp4 video. E.g: "http://media.blacktrash.org/stsp.m3u8" worked fine for me on Samsung 2014.

Regards,
Radim

**Comment by radimbuchtela** [comment]
We gave answer regarding the similar issue from Samsung Support. 
14TV_STANDARD1 (X14) model group player driver doesn't support framerate change during playing.

I analyzed stream: http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8 by ffprobe tool and 
I see the frame rate is changing from 15 fps to 30 fps:

1) Stream with bandwidth 688301
first segment: http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/0640/06400.ts (from http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/0640_vod.m3u8)
It has 30 fps

2) Stream with bandwidth 262346
first segment: http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/0240/02400.ts (from http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/0240_vod.m3u8)
It has 15 fps

Radim

**Comment by macfanr** [comment]
is there a sample M3U8 that can be played on Samsung TV?
