### ISSUE TITLE
Scroll Long List in view

### ISSUE THREAD

**Issue by naja7host** [mautilus/sdk#38]
i have a app that has a long list inside (ul) . when we scroll in the list it go to down and the focus item not remain in the view . 

is their any code or practice to do with  long list in that sdk ?

**Comment by SoCoxx** [comment]
You have to maintain focus in the viewport of snippet/scene. Take a look at http://sdk-example-2.mine.sk/

Snippet with "covers" is wrapped in overflow:hidden div and negative "top" is following the focus. It is the method scrollToFit in http://sdk-example-2.mine.sk/js/snippet/grid.js

Take it as an example, as it probably won't work if you just copy&paste it into your project :)

**Comment by naja7host** [comment]
a big thanks , this is what i need totally , i love the idea of scrolling (left/right and between the items and the menu ..... can i get the full source ?

**Comment by SoCoxx** [comment]
http://sdk-example-2.mine.sk/example.zip

Enjoy :)

**Comment by naja7host** [comment]
another big thank .

**Comment by naja7host** [comment]
Sorry to reopen this issue . 

I want to add lazyload jquery effect for images. I have a big list retrieved via ajax and the page take more time to load .

I have added the lazyload function in the snipppet onscroll() function but is not working . 

Any more help in this ? Thanks in advance .
