### ISSUE TITLE
build package

### ISSUE THREAD

**Issue by naja7host** [mautilus/sdk#39]
how we can build the package for multiple devices ? 

any howto for this ?

**Comment by radimbuchtela** [comment]
Hi,
there could be helpful these 2 following threads regarding your topic:
- https://github.com/mautilus/sdk/issues/15 Compile/Export project to each platform
- https://github.com/mautilus/sdk/issues/32 General question on SDK and packaging

If something is not clear, please ask us for next details.

Regards,
Radim

**Comment by naja7host** [comment]
but how we can use the Gruntfile.js ? 
i have lanced the install.bat but it only install the nmp module .
