### ISSUE TITLE
Vestel devices

### ISSUE THREAD

**Issue by jorgitoml** [mautilus/sdk#40]
I don't seee the Vestel device detection code in the getDevice function. 
Is this a bug or Vestel devices are treated as generic devices.
Regards.

**Comment by radimbuchtela** [comment]
Hi,
you are right. Vestel device detection is missing in the Main.getDevice().

According to project where Vestel driver is used, detection is done as 
``` javascript
} else if (navigator.userAgent.indexOf('HYUNDAI') >= 0 || navigator.userAgent.indexOf('GOGEN') >= 0 || navigator.userAgent.indexOf('SHARP') >= 0 || navigator.userAgent.indexOf('VESTEL') >= 0) {
    return ['vestel', ''];
}
```

But I cannot confirm it still works on 100%.

Radim
