### ISSUE TITLE
store array in storage

### ISSUE THREAD

**Issue by naja7host** [mautilus/sdk#48]
WhT is the best approuch to store an array with the storage plugin ?

**Comment by radimbuchtela** [comment]
Hi naja7host,
you can use Storage object from SDK: http://smarttv.mautilus.com/SDK/#!/api/Storage

```
var array = [1, 2, 3];
Storage.set("myArray", array);  // to store your array

var storedArray = Storage.get("myArray");  // to receive your array
```

Regards,
Radim
