### ISSUE TITLE
how to make ajax request the cross domain using this sdk?

### ISSUE THREAD

**Issue by kingctan** [mautilus/sdk#6]
Hello, I recently use your sdk to make a ajax request to other domain but failed all the time. I can't find a helpful way to resolve this problem, can you give any advice? thanks.

**Comment by kingctan** [comment]
ok,I add  a proxy server to solve this problem.

**Comment by SoCoxx** [comment]
If you are using JSON, you might fail on XMLHttpRequest same domain policy. To overcome this problem, you need to add Cross-Origin Resource Sharing HTTP headers in server responses (by server itself, or via proxy). In PHP like:
<?
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
$headers = apache_request_headers();
if (array_key_exists('Content-Type',$headers) && $headers['Content-Type'] != '') {
   header('Content-Type: '.$headers['Content-Type']);
}
print file_get_contents($_GET['url']);
?>

And calling it: "http://your.domain/script.php?url=http://other.domain/url/resource.json"

Or you can use JSONP, where XMLHttpRequest same domain policy is tricked by jQuery by creating <script> elements, and parsing data from them. Disadvantages:
- you need to have JSONP responses enveloped in callback function to pair requests with responses: someCallback({"key":"value"});
- you have no control about the requests . I.e. you can't add headers to JSONP request, as it is made not by jQuery, but browser core (via <script> tag as describer above), or cancel request, etc.

**Comment by kingctan** [comment]
Thank @SoCoxx ,
I have tried the JSONP, but It also need the server support the callback, if not, the client get failed response and get the info: parse error.

**Comment by SoCoxx** [comment]
Are you getting this error on TV, or while testing in Chrome?

**Comment by stenlik** [comment]
As @SoCoxx mentioned, the best way is to allow CORS on server responses. My question is on which platform you have such issue? Is your application hosed? When the application is installed and executed locally on LG and Samsung there is none problem with CORS.

**Comment by kingctan** [comment]
@stenlik I run on samsung TV, and the server is run locally on tomcat server which developed by other memeber,so I can't change anythings in the server side.
same as this problem: http://stackoverflow.com/questions/23730216/jsonp-parse-error-with-jquery-ajax-request
Thanks.

**Comment by stenlik** [comment]
If the application is installed and started locally from Samsung TV there is no CORS check, so you should not have any CORS related issues. CORS issues occurs only when the application is hosted.
