### ISSUE TITLE
the div in scene overflow-y set to auto but it can't scroll using remote control.

### ISSUE THREAD

**Issue by kingctan** [mautilus/sdk#8]
the div in scene overflow-y set to auto but it can't scroll using remote control.
please help.

**Comment by SoCoxx** [comment]
This is not covered by the Mautilus SDK. Scrolling must be programmed in the application, as there are plenty of ways, how the scrolling should behave

**Comment by kingctan** [comment]
OK,Thanks @SoCoxx .
