### ISSUE TITLE
how to add customized drm support,such as verimatrix drm?

### ISSUE THREAD

**Issue by kingctan** [mautilus/sdk#9]
how to add customized drm support,such as verimatrix drm?

**Comment by stenlik** [comment]
All Verimatrix related information are released under NDA. Just be aware - it is not a simple task. You need to have good support from Verimatrix, TV vendors, set of test streams and minimum 10+ TVs for testing per vendor.

**Comment by stenlik** [comment]
Hi,

Did the answer help you? If yes please close the issue.

Thanks
Mautilus SmartTV SDK Team

**Comment by kingctan** [comment]
Hello @stenlik , sorry for long time no close for this thread.
I test the verimatrix drm for some days.
But I failed for this integration when sendDrmMessage:
I got an error:
errorcode:500
errortext: Vendor Managed Error: 1

and when click play button again:
error changed:
errorcode:501
errortext:This API is not supported in the activated drm.

Can you please help give any advise, if the drm server configuration error or any other module?
Thanks a lot.

BTW: the verimatrix drm load is successed!

**Comment by stenlik** [comment]
Hello,

We are not allowed to provide any information about Verimatrix. I am sorry for that, but all information are released under NDA. Please contact your Verimatrix account manager.

Thank you for understanding
Mautilus SmartTV SDK Team
